### ISSUE TITLE
TODO list before 1st release

### ISSUE THREAD

**Issue by pascalgrimaud** [hipster-labs/generator-jhipster-spring-cloud-stream#4]
Here a TODO list before the 1st release of this module:

- [x] add properties to yaml -> done in https://github.com/hipster-labs/generator-jhipster-spring-cloud-stream/pull/7
- [x] Travis: add real tests on an existing project -> by @pascalgrimaud, fixed by https://github.com/hipster-labs/generator-jhipster-spring-cloud-stream/pull/9
    - launch this generator on existing project
    - mvn compile and test
    - start the project -> not need I think
- [x] yeoman banner -> fixed by https://github.com/hipster-labs/generator-jhipster-spring-cloud-stream/pull/10
- [x] improve README -> https://github.com/hipster-labs/generator-jhipster-spring-cloud-stream/pull/16
- [x] propose a name at prompt, for not using Message but a custom class, so it won't conflict with possible existing class -> add by https://github.com/hipster-labs/generator-jhipster-spring-cloud-stream/pull/14. for test.
- [x] forbid the use of this generator when Kafka is already used (and other options?) -> https://github.com/hipster-labs/generator-jhipster-spring-cloud-stream/pull/18
- [x] Correct issue https://github.com/hipster-labs/generator-jhipster-spring-cloud-stream/issues/13 -> fixed by https://github.com/hipster-labs/generator-jhipster-spring-cloud-stream/pull/14
- [x] Add unit test on util.js -> fixed by https://github.com/hipster-labs/generator-jhipster-spring-cloud-stream/pull/11

Bug:
- [x] rename `MessageRessource` to `MessageResource` -> fixed by https://github.com/hipster-labs/generator-jhipster-spring-cloud-stream/pull/5

Helped by: https://github.com/danielpetisme/jhipster-sample-app-rabbitmq
The diff: https://github.com/danielpetisme/jhipster-sample-app-rabbitmq/compare/master...rabbit-binder

Don't hesitate to edit this ticket.

**Comment by antarus** [comment]
The addi of property is made but it does not please me at all.
I need to find a way to just modify the original yaml and not rewrite it completely. Currently the formatting is not good, the original comments of yaml are deleted.

Added a property in the file is not complicated, if it is put at the end or beginning of the file.
The problem is if i want to add a property with one or more common. Spring.cloud.etc .. I try but regex  it's not my cup of tea: D

**Comment by antarus** [comment]
As kafka does not manage for the moment in our module, should not we block the generation if the main application uses kafka?

**Comment by pascalgrimaud** [comment]
Yes, we should block if Kafka is already used!
No need to use both

**Comment by danielpetisme** [comment]
Actually you can have both binders (technically speaking). The binder could be an option list with at least one choosen.

**Comment by antarus** [comment]
yes we should have a list of message broker to display.

**Comment by pascalgrimaud** [comment]
@antarus :
- currently, in master, I added a fixed version 1.3.0.RELEASE, for the dependencies, otherwise it won't compile
- now I understand your PR https://github.com/jhipster/generator-jhipster/pull/6667 : there is a missing dependencyManagement here

We won't be able to use these functions unless there is a new release of JHipster. 
And it won't work for project older than 4.10.2

Here the solution I suggest, which works for older projects and newer:
- if the functions exists, use them and add dependencies management, no need to specify the version
- if the functions doesn't exist:
   - add fixed version, 1.3.0.RELEASE
   - then, add a warning to the user, so he can manually add the missing dependency management.

Are you OK with that ?

**Comment by antarus** [comment]
Exactly, I tested only with the generator locally ...sorry ! 
I would not make the same mistake with switching the yaml code to the main generator, I'll wait for a release before deleting it here.

Yes, we can do it according to your suggestion, it seems to me a good solution.

**Comment by antarus** [comment]
@pascalgrimaud 
Since we just need to add properties to the yaml file, I'll do the update and delete methods later if need.

**Comment by pascalgrimaud** [comment]
it's ok, let's do it later

**Comment by antarus** [comment]
I correct the anomaly and I try the prompt. I pull request later.

**Comment by pascalgrimaud** [comment]
@antarus : are you ok to change the main author (pascalgrimaud -> you), as you are the one who coded the most for this module? It won't change anything, as it will be still under Apache Licence.

If yes, these files need to be changed:
- README
- package.json

Then, you will be the one to publish the module to https://www.npmjs.com/

**Comment by antarus** [comment]
@pascalgrimaud 
Hello, originally, I just wanted to participate and help the jhipster project, since I use it in my company.
I did not even use rabbit, this module seemed to me a good base to develop a module with jhipster and give me a preview of the generator.
So I'm not sure I'm the best person to manage the npm delivery (which I've never done before: D). I just want to help, add features, for example,
I did not find how to integrate this module with the main generator. let me explain :
- How to make this module can perform particular treatments when using the sub-generator docker-compoose, ci, etc.
- How to register this module, to add the choice of kafka when choosing other technologies.

**Comment by pascalgrimaud** [comment]
It's OK, I will do release, it's quite simple. If one day you change your mind, I can give you the lead on this.

About your questions. The workflow is:
- the user generated a JHipster application
- then, he will use this module to add RabbitMQ to his project. The support is really simple
    - add dependencies
    - add properties in configuration file
    - add docker-compose file
    - add some sample classes to test the new support
- if the user uses docker-compose sub-generator, RabbitMQ won't be in the generated docker-compose file. He needs to add it manually -> less than 10 lines of codes
- it's the same for ci-cd, kubernetes, openshift etc... he needs to add manually
- this module is totally independent from the main generator-jhipster, so it can't be part of the 'other technologie'

**Comment by antarus** [comment]
OK.
I agree that the workflow is simple and changes can be made quickly for this module.
It seemed to me that the main generator supported module registration to perform certain actions.
I have a module and I would like to improve the integration of modules in the main generator. I'm going to think about that, see doing a POC and make a suggestion directly in generator-jhipster.

We are close to a first release it's nice: D

**Comment by pascalgrimaud** [comment]
Yes, but let's do the release after the official release of generator-jhipster
See https://groups.google.com/forum/#!topic/jhipster-dev/rOLxkeCtPYI

**Comment by antarus** [comment]
yes !

**Comment by pascalgrimaud** [comment]
I will try to:
- remove gulp
- test everything with JHipster 4.11.0

If everything is OK, let release !

**Comment by pascalgrimaud** [comment]
@antarus : do you have Twitter? I want to mention you as soon as this is released.

**Comment by pascalgrimaud** [comment]
Release done!
https://twitter.com/pascalgrimaud/status/935413124294995969

Thanks for your hard work, @antarus

**Comment by antarus** [comment]
yes ;) 
it's cool !
